<div id="myNav" class="overlay" style="z-index:5">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav();" style="z-index:6">&times;</a>
    <div class="overlay-content">
        <div class="w3-row-padding w3-margin-bottom w3-margin">
            <p><strong>Privacy Policy</strong></p>
            <p>This Privacy Policy describes the policies and procedures MySen PLT. (“we”, “our” or “us”) on the collection, use and disclosure of your information in connection with your use of the MySen application (the “App”) and any associated services, features, content or applications we offer through the App (collectively, the “Services”). We receive information about you from various sources, including without limitation: (i) if you register for the App and the Services, through your user account on the Services (your “Account”); (ii) your use of the Services generally; and (iii) from third party websites and services. When you use the Services, you are consenting to the collection, transfer, manipulation, storage, disclosure and other uses of your information as described in this Privacy Policy.</p>
            <br/>
            <p><strong>What Does This Privacy Policy Cover?</strong></p>
            <p>This Privacy Policy covers the treatment of personally identifiable information (“Personal Information”) gathered when you are using or accessing the Services. This Privacy Policy also covers our treatment of any Personal Information that our business partners share with us or that we share with our business partners.</p>
            <p>This Privacy Policy does not apply to the practices of third parties that we do not own or control, including but not limited to any third party websites, services and applications (e.g. Spotify, iTunes, YouTube, Google Play, Twitter, Facebook, Instagram, etc.) (each a “Third Party Service”) that you elect to access through the Service or to individuals that we do not manage or employ. While we attempt to facilitate access only to those Third Party Services that share our respect for your privacy, we cannot take responsibility for the content or privacy policies of those Third Party Services. We encourage you to carefully review the privacy policies of any Third Party Services you access.</p>
            <br/>
            <p><strong>What Information Do We Collect?</strong></p>
            <p>The information we gather enables us to personalize, improve and continue to operate the Services. In connection with certain aspects of the Services, we may request, collect and/or display some of your Personal Information. We collect the following types of information from our users.</p>
            <p><strong>Account Information:</strong></p>
            <p>If you create an account on the Services (“Account”), you may be required to provide information that could be Personal Information, such as your name, phone number and/or email address. Additionally, if you register for or access the Services using a Third Party Service (such as your social media account login credentials), we may receive Personal Information that you allow such Third Party Service to share with us. You acknowledge that this information may be personal to you, and by creating an Account and providing Personal Information to us, you allow others, including us, to identify you and therefore may not be anonymous. We may use your contact information to send you information about our Services. You may unsubscribe from some of these messages by emailing us at info@mysen.org, although we, regardless, reserve the right to contact you when we believe it is necessary, such as for account recovery purposes.</p>
            <p><strong>Information Regarding Your Social Networks:</strong></p>
            <p>As mentioned above, you may be able to register for or access the Services using a Third Party Services, such as your social media account (e.g. Facebook, Twitter, Instagram, etc.). Occasionally, you can also use your Account on our Services to interact with your accounts on these other services. For example, you may be able to access posting and sharing tools on the Services that allow you to post information to your social networks outside of the Services (“Share”). By using these tools, you acknowledge that some account information from your account on the applicable Third Party Service may be transmitted into your Account with us, and that such information is covered by this Privacy Policy. Furthermore, if a tool, such as the Share tool, is operated by a Third Party Service, the Third Party Service that operates the tool may collect information about your browser or online activity, which would be subject to the Third Party Service’s privacy policy. When you use these tools, some of your information from the Services may be shared with the Third Party Service and others. Therefore, we encourage you to read the privacy policies and other policies of any Third Party Services, including without limitation any applicable social networks, you use in connection with the Services.</p>
            <p>Additionally, we may collect and receive your social media account login credentials in connection with providing you with the Services, but only if you expressly provide us with such information. We will only use such login information as set forth in this Privacy Policy or as otherwise expressly authorized by you.</p>
            <p><strong>User Content:</strong></p>
            <p>Some features of the Services allow you to provide content to the Services, such as video clips. All content submitted by you to the Services may be retained by us indefinitely, even after you terminate your Account. We may continue to disclose such content to third parties in a manner that does not reveal Personal Information, as described in this Privacy Policy.</p>
            <p><strong>Location Information:</strong></p>
            <p>Some of our Services may include features based on users’ actual locations and may report on users’ current locations (“Location-Based Services”). To the extent you voluntarily opt to use any Location-Based Services, we may collect and store information about your location at the time you use those Location-Based Services. Additionally, we may also collect and/or receive location information from your use of the Services generally, which can come from a variety of sources, depending on how you use or access the Services. For example, a User Image taken from your mobile device may contain location information related to where the image was taken, or a mobile device may report its GPS location at the time Location-Based Services are used.</p>
            <p><strong>IP Address Information and Other Information Collected Automatically:</strong></p>
            <p>• Generally, the Services automatically collect usage information, such as the number and frequency of visitors to the App and users of the Services. We may use this data in aggregate form, that is, as a statistical measure, or in other anonymous forms, but not in a manner that would identify you personally. This type of data enables us and third parties authorized by us to figure out how often individuals use parts of the Services so that we can analyze and improve them.</p>
            <p>• We automatically receive and record information from your web browser and device when you interact with the Services, including your IP address and cookie information and other mobile identifiers. This information is used for fighting spam/malware and also to facilitate collection of data concerning your interaction with the Services (e.g., what links you have clicked on).</p>
            <p>• We may collect some device-specific information if you access the Services using a mobile device. Device information may include but is not limited to unique device identifiers, network information, and hardware model, as well as information about how the device interacts with our Services.</p>
            <p><strong>Email, Text, and Push Notification Communications:</strong></p>
            <p>We may communicate with you via push notification, email, SMS, MMS or other text message (“Message”) (to the extent you permit us to do so), and we may collect information regarding such communications, such as confirmation when you open an email, read a Message or receive a push notification. We use this information to improve our Services, including without limitation our customer service.</p>
            <p><strong>Aggregate Information</strong></p>
            <p>We collect statistical information about how both unregistered and registered users, collectively, use the Services (“Aggregate Information”). Some of this information is derived from Personal Information. This statistical information is not Personal Information and cannot be tied back to you, your Account or your web browser.</p>
            <br/>
            <p><strong>How, and With Whom, Is My Information Shared?</strong></p>
            <p><strong>Public Information About Your Activity on the Services:</strong></p>
            <p>Some of your activity on and through the Services is public. This may include, but is not limited to, content you have posted publicly on, through or in connection with the Services, including without limitation on public portions of Third Party Services, such as your social media accounts.</p>
            <p>Registered users may have some of this information associated with their Accounts. Unregistered users will not have this association, but information concerning their use of the Services (such as what pages they have visited) may be tracked anonymously through the use of cookies and stored by us.</p>
            <p>Please remember that if you choose to provide Personal Information using certain public features of the Services, then that information is governed by the privacy settings of those particular features and may be publicly available. Individuals reading such information may use or disclose it to other individuals or entities without our control and without your knowledge, and search engines may index that information. We therefore urge you to think carefully about including any specific information you may deem private in content that you create or information that you submit through the Services.</p>
            <p><strong>IP Address and Device Information:</strong></p>
            <p>While we collect and store IP address and device information, that information is not made public. We do at times, however, share this information with our partners, service providers and other persons with whom we conduct business, and as otherwise specified in this Privacy Policy.</p>
            <p><strong>Information You Elect to Share:</strong></p>
            <p>You may access other Third Party Services through the Services, for example by clicking on links to those Third Party Services from within our Services. We are not responsible for the privacy policies and/or practices of these Third Party Services, and you are responsible for reading and understanding those Third Party Services’ privacy policies. This Privacy Policy on</p>


            <br/>
            <p><strong>Terms of Use</strong></p>
            <br/>
            <p><strong>IMPORTANT NOTICE:</strong></p>
            <p>Please read these Terms of Use (collectively with the MySen PLT “Terms of Use”) fully and carefully before using the MySen application (the “App”) and the services, features, content or applications offered by MySen PLT in connection with the App (“Company,” “we”, “us” or “our”) (together with the App, the “Services”). These Terms of Use set forth the legally binding terms and conditions for your use of the App and the Services.</p>

            <br/>
            <p><strong>Acceptance of Terms of Use.</strong></p>
            <p>By signing up for, installing and/or using the App in any manner, you agree to these Terms of Use and all other operating rules, policies and procedures that may be published from time to time through the App by us, each of which is incorporated by reference and each of which may be updated from time to time without notice to you.</p>
            <p>Certain Services may be subject to additional terms and conditions specified by us from time to time; your use of such Services is subject to those additional terms and conditions, which are incorporated into these Terms of Use by this reference, including without limitation the MySen Tournament Official Rules.</p>
            <p>These Terms of Use apply to all users of the Services, including, without limitation, users who are contributors of content, information, and other materials or services, registered or otherwise.</p>
            <p><strong>Eligibility.</strong> You represent and warrant that you are an individual person at least 18 years of age. If the entrant is below the age of 18, parental or legal guardian consent is required. By joining this contest, the parent/legal guardian of the underaged entrant agrees to the [Terms of Use] on behalf of the entrant. We may, in our sole discretion, refuse to offer the Services to any person or entity and change its eligibility criteria at any time. You are solely responsible for ensuring that these Terms of Use are in compliance with all laws, rules and regulations applicable to you and the right to access the Services is revoked where these Terms of Use or use of the Services is prohibited or to the extent offering, sale or provision of the Services conflicts with any applicable law, rule or regulation. Further, the Services are offered only for your use, and not for the use or benefit of any third party. You are not eligible for our Contests if you violate any provision of these Terms, as determined in MySen’s sole discretion.</p>
            <p><strong>Registration.</strong> To sign up for the Services, we may require you to register for an Account on the Services (an “Account”) or log in via Facebook Connect, or another authentication mechanism (a “Third Party Account”). You must provide accurate and complete information and keep your Account information updated. If you provide any information that is inaccurate, not current or incomplete, or Company has reasonable grounds to suspect that such information is inaccurate, not current or incomplete, Company may deny you access to Contests, areas requiring registration, disqualify you from Contests, revoke Prizes, and/or terminate your Account, at its sole discretion. You shall not: (i) select or use as a username a name of another person with the intent to impersonate that person; (ii) use as a username a name subject to any rights of a person other than you without appropriate authorization; or (iii) use, as a username, a name that is otherwise offensive, vulgar or obscene. You are solely responsible for the activity that occurs on your Account, and for keeping your Account password and login credentials secure. You may never use another person’s user Account or registration information for the Services without permission. You must notify us immediately of any change in your eligibility to use the Services (including any changes to or revocation of any licenses from state authorities), breach of security or unauthorized use of your Account. You should never publish, distribute or post login information for your Account. You shall have the ability to delete your Account, either directly or through a request made to one of our employees or affiliates. You may create, maintain, use and control only one Account on the Service. Each Account on the Service may only be owned, maintained, used and controlled by one individual. For avoidance of doubt, users may not “co-own” or share the same account on the Service. In the event Company determines that you have opened, maintained, used or controlled more than one Account, in addition to any other rights that Company may have, Company reserves the right to suspend or terminate any or all of your accounts and terminate, withhold or revoke the awarding of any Prizes.</p>
            <p><strong>Content Definition.</strong> For purposes of these Terms of Use, the term “Content” includes, without limitation, information, data, text, photographs, videos, audio clips, written posts and comments, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible on or through the Services. For the purposes of this Agreement, “Content” also includes all User Content (as defined below).</p>
            <p><strong>User Content.</strong> All Content added, created, uploaded, submitted, distributed, or posted to the Services by users (collectively “User Content”), whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such User Content. You represent that all User Content provided by you is accurate, complete, up-to-date, and in compliance with all applicable laws, rules and regulations. You retain ownership of any and all User Content created and/or uploaded by you. You acknowledge that all Content, including User Content, accessed by you using the Services is at your own risk and you will be solely responsible for any damage or loss to you or any other party resulting therefrom. We do not guarantee that any Content you access on or through the Services is or will continue to be accurate.</p>
            <p><strong>Notices and Restrictions.</strong> The Services may contain Content specifically provided by us, our partners or our users and such Content is protected by copyrights, trademarks, service marks, patents, trade secrets or other proprietary rights and laws. You shall abide by and maintain all copyright notices, information, and restrictions contained in any Content accessed through the Services.</p>
            <p><strong>Use License.</strong> Subject to these Terms of Use, we grant each user of the Services a worldwide, non-exclusive, non-sublicensable and non-transferable license to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution or storage of any Content (other than your User Content) for other than purposes of using the Services is expressly prohibited without prior written permission from us. You shall not sell, license, rent, or otherwise use or exploit any Content (other than your User Content) for commercial use or in any way that violates any third party right.</p>
            <p><strong>License Grant.</strong> By submitting User Content through the Services, you hereby do and shall grant us a worldwide, non-exclusive, perpetual, royalty-free, fully paid, sublicensable and transferable license to use, edit, modify, manipulate, truncate, aggregate, reproduce, distribute, prepare derivative works of, display, perform, and otherwise fully exploit the User Content in connection with the App, the Services and our (and our successors’ and assigns’) businesses, including without limitation for promoting and redistributing part or all of the App or the Services (and derivative works thereof) in any media formats and through any media channels (including, without limitation, third party websites and feeds), and including after your termination of your Account or the Services. For the sake of clarity, to the extent any User Content you submit includes your name, likeness, voice, video, or photograph, you acknowledge and agree that the foregoing license of this Section 4(e) shall apply to the same. You also hereby do and shall grant each user of the App and/or the Services a non-exclusive, perpetual license to access your User Content through the App and/or the Services, and to use, edit, modify, reproduce, distribute, prepare derivative works of, display and perform such User Content, including after your termination of your Account or the Services. For clarity, the foregoing license granted to us and our users does not affect your other ownership or license rights in your User Content, including the right to grant additional licenses to your User Content, unless otherwise agreed in writing. You represent and warrant that you have all rights to grant such licenses to us without infringement or violation of any third party rights, including without limitation, any privacy rights, publicity rights, copyrights, trademarks, contract rights, or any other intellectual property or proprietary rights.</p>
            <p><strong>Availability of Content.</strong> We do not guarantee that any Content will be made available on the App or through the Services. We reserve the right to, but do not have any obligation to, (i) remove, edit or modify or otherwise manipulate any Content in our sole discretion, at any time, without notice to you and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if we are concerned that you may have violated these Terms of Use), or for no reason at all and (ii) to remove or block any Content from the Services.</p>

            <br/>
            <p><strong>Rules of Conduct.</strong></p>
            <p>As a condition of use, you promise not to use the Services for any purpose that is prohibited by these Terms of Use. You are responsible for all of your activity in connection with the Services. Violation of our rules may result in the termination and cancellation of your Account and forfeiture of your winnings. You acknowledge and agree that we may terminate any MySen Account at any time for any reason (including, but not limited to, our independent assessment or the receipt of claims or allegations from</p>

        </div>
    </div>
</div>
